name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build apk and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set Up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true

      - name: Build ARMv7 debug and minified APKs
        run: ./gradlew assembleDebug assembleReleaseWithDebugSigning

      - name: Run Local Tests
        run: ./gradlew test

      - name: Lint Checks
        run: ./gradlew ktlintCheck

      - name: Upload Player ARMv7 APK
        uses: actions/upload-artifact@v7
        with:
          name: Player-armv7
          path: ./app/build/outputs/apk/release-with-debug-signing/app-armeabi-v7a-release-with-debug-signing.apk

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: build-reports
          path: app/build/reports
